### ISSUE TITLE
Shuffle option

### ISSUE THREAD

**Issue by LoyVanBeek** [Rayman/fusic-meteor#105]

**Comment by pepf** [comment]
+1

2015-11-24 20:37 GMT+01:00 Loy <notifications@github.com>:

**Comment by reinzor** [comment]
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

**Comment by pepf** [comment]
Available for testing on http://fusic.herokuapp.com :ok_hand: 
<img width="301" alt="screen shot 2015-11-29 at 22 21 50" src="https://cloud.githubusercontent.com/assets/1265435/11460147/a415a8ce-96e7-11e5-8b8d-c07e874e18b0.png">

**Comment by LoyVanBeek** [comment]
Awesome :+1: :ok_hand:
